basePath: /v1
host: 192.168.0.158:9000
info:
  contact:
    name: Skyler
  description: swagger test example
  title: Linhome
  version: "1.0"
paths:
  /user/Login:
    get:
      consumes:
      - application/json
      description: 使用者登入功能
      parameters:
      - description: 使用者名稱
        in: query
        name: username
        required: true
        type: string
      - description: 密碼
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登入成功
          schema:
            type: string
        "400":
          description: 請求失敗
          schema:
            type: string
      summary: 登入
      tags:
      - User
    post:
      consumes:
      - application/json
      description: 使用者登入功能
      parameters:
      - description: 使用者名稱
        in: query
        name: username
        required: true
        type: string
      - description: 密碼
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登入成功
          schema:
            type: string
        "400":
          description: 請求失敗
          schema:
            type: string
      summary: 登入
      tags:
      - User
schemes:
- http
swagger: "2.0"
